### ISSUE TITLE
Siege error!

### ISSUE THREAD

**Issue by Dylen67** [Jonathan57500/aion-lightning-2.7#16]
Hi!

console log:

2018-09-28 12:00:01,695 WARN  [pool-4-thread-1] com.aionemu.gameserver.services.siegeservice.Siege [Siege.java:207] [TEST] BOSS 1 :260010 | BOSS 2 :260010
2018-09-28 12:00:01,766 WARN  [pool-4-thread-1] com.aionemu.commons.utils.concurrent.ExecuteWrapper [ExecuteWrapper.java:49] Exception in a Runnable execution:
com.aionemu.gameserver.services.siegeservice.SiegeException: Found 2 siege bosses for outpost 1011

**Comment by Jonathan57500** [comment]
This is a warning, not an error. Well a warning is not a good news but your server will work normally.

**Comment by Dylen67** [comment]
Why does 2 Boss load?
"[TEST] BOSS 1 :260010 | BOSS 2 :260010"
How to Remove One Booss?
No automatic Balaur assaults.

Thanks

**Comment by Jonathan57500** [comment]
It looks like it is an isolated problem, for example because some scheduled jobs where not launched correctly.
Please do not open an issue each time you have a warning, it's impossible to reproduce the same problem without more data. You can open a new issue here if you have the same problem a few times, and then added more data to try to debug it.
Anyway thanks for your participating :)

**Comment by Dylen67** [comment]
I solved
Thanks
