### ISSUE TITLE
System Requirements of the emulator

### ISSUE THREAD

**Issue by Disctanger** [Jonathan57500/aion-lightning-2.7#3]
Good day, @Jonathan57500 
Again I will bother you with some questions :smiley: 
Before I remember that I used to allocate 2 GB RAM for the emulator, but I did not know how much do I need to allocate.
1. How much RAM does emulator need for solely running the emulator?
2. How much RAM does emulator need per single connection (player)?
3. Does emulator support multi-threading (saying it easier: is there any meaning running the emulator on dual-core or quad core server which will run only this emulator and no other software)?

Sorry for directly asking question but I think this will make it easy to understand for other readers.

At the moment I am preparing environment for the emulator. Currently I am (king of) bit busy with other stuffs but I am thinking of joining development after some time.

**Comment by Jonathan57500** [comment]
Hi @Disctanger 
Don't worry, I love people who ask questions, and later your questions will be probably moved into FAQ page of this project ;)
It's hard to give an answer for your questions because it's depending of what kind of server you have: Linux, Windows, 32/64bits, what version, etc.
I've just started my server to give you an idea:

1. Game Server: 1655 MB Login Server 105 MB
2. It's not possible to calculate RAM per player, it's depends of what they are doing, where they are, if they are together or on different maps, etc. I would say something like +500MB per 10 players from 1 to 50, +250 MB per 10 players from 51 to 75, something like that.
![2018-01-17_19h34_33](https://user-images.githubusercontent.com/20670942/35060057-76aaaffa-fbbd-11e7-860d-39ff73db1434.png)
3. Yes, see previsous screenshot and:
![2018-01-17_19h35_49](https://user-images.githubusercontent.com/20670942/35060107-9e2aa8b4-fbbd-11e7-9e1d-4354806eed92.png)

I'll be very happy if you decide to join dev team (hmm... Now team = me and myself :D) There is a lot of code to do here to fix issues and add new dynamic content ;)

**Comment by Jonathan57500** [comment]
Hi @aionchs I'm happy to read this ;)
It does not bother me to chat out of this depot but we must not post any dev info into Facebook, the purpose of this deposit is to centralize all code data regarding this emulator.
I've created a Facebook group for test, you can join it as free, but remember to ask question and report bugs directly on this github depot not on Facebook.
https://www.facebook.com/groups/1004324073054233/
